using System.Diagnostics;
using System.Text.RegularExpressions;

namespace HtmlMinifier;

public class NodeRunner
{
    public bool ReadFile(string filePath, ref string content, ref string directoryFile)
    {
        try
        {
            if (File.Exists(filePath))
            {
                Thread.Sleep(100);
            
                directoryFile = Path.GetDirectoryName(filePath);
            
                content = File.ReadAllText(filePath);
                return true;
            }
            
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            
        }
       
        return false;
        
    }


    public string GetAllJsScripts(string directoryFile, string content)
    {
        var scripts = Regex.Matches(content, "((<script>)|(<script))[\\w\\W]+?<\\/script>").Select(a => a.Value)
            .ToList();

        List<string> scriptsCode = new List<string>();

        foreach (var script1 in scripts)
        {
            if (Regex.IsMatch(script1, @"((<script>)|(<script))[\w\W]+?><\/script>"))
            {
                string srcPath = Path.GetFullPath(
                    Path.Combine(directoryFile,
                        Regex.Match(script1, @"src=?"".+?""").Value.Replace("src=\"", string.Empty)
                            .Replace("\"", string.Empty))
                );
                if (File.Exists(srcPath))
                    scriptsCode.Add(File.ReadAllText(srcPath));
            }
            else
            {
                scriptsCode.Add(script1.Replace("<script>", string.Empty).Replace("</script>", string.Empty));
            }
        }

        return string.Join("\n\n", scriptsCode);
    }


    public string RmoveAllScripts(string content)
    {
        return Regex.Replace(content, "((<script>)|(<script))[\\w\\W]+?<\\/script>", string.Empty);
    }

    public string GetCppH( string code )
    {
        return @"
#ifndef WEBUI_H
#define WEBUI_H
const char* htmlContent = R""rawliteral(
{{WEBUI}}
)rawliteral"";
#endif
".Replace("{{WEBUI}}", code);
    }
    
    public string GethtmlMinifierJs()
    {
        return @"
var fs = require('fs');


var minify = require('html-minifier').minify;
 



// Имена файлов
var inFile = '{{IN_FILE}}'; // Замените на имя входного файла, например, 'input.html'
var outFile = '{{OUT_FILE}}'; // Замените на имя выходного файла, например, 'output.html'

// Читаем HTML из файла
fs.readFile(inFile, 'utf8', function (err, data) {
  if (err) {
    return console.error('Ошибка при чтении файла:', err);
  }

  // Минифицируем данные из файла
  var result = minify(data, {
      includeAutoGeneratedTags: true,
      removeAttributeQuotes: true,
      removeComments: true,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      sortClassName: true,
      useShortDoctype: true,
      collapseWhitespace: true
  });

  // Сохраняем минифицированный результат в файл
  fs.writeFile(outFile, result, function (err) {
    if (err) {
      return console.error('Ошибка при записи файла:', err);
    }
    console.log('Файл успешно сохранен в', outFile);
  });
});

";
    }

    public string GetscriptMiniferJs()
    {
        return @"

const fs = require('fs').promises;
const { minify } = require('terser');

async function minifyFile(inputFilePath, outputFilePath) {
    try {
        // Read the input file
        const code = await fs.readFile(inputFilePath, 'utf8');
        
        // Minify the code
        const result = await minify(code, { sourceMap: true });

        // Save the minified code to the output file
        await fs.writeFile(outputFilePath, result.code, 'utf8');

        console.log('Minification successful! Minified code saved to:', outputFilePath);
    } catch (error) {
        console.error('Error during minification:', error);
    }
}

// Usage example:
const inputPath = '{{IN_FILE}}'; // Replace with your input file path
const outputPath = '{{OUT_FILE}}'; // Replace with your output file path
minifyFile(inputPath, outputPath);

";
    }

    public void CopressCodeToFile(string pathMiniJs, string pathMiniHtml, string outputPath)
    {
      

        string contentJs = "";
        string directoryFileJs = "";
        
        string contentHtml = "";
        string directoryFileHtml = "";
        if (ReadFile(pathMiniJs, ref contentJs, ref directoryFileJs) && ReadFile(pathMiniHtml, ref contentHtml, ref directoryFileHtml))
        {
            string fillHtmlCode = contentHtml.Replace("</body>", $"<script>{contentJs}</script></body>");
            File.WriteAllText(outputPath , fillHtmlCode);
        }
    }
    public string CopressCode(string pathMiniJs, string pathMiniHtml )
    {
      

        string contentJs = "";
        string directoryFileJs = "";
        
        string contentHtml = "";
        string directoryFileHtml = "";
        if (ReadFile(pathMiniJs, ref contentJs, ref directoryFileJs) && ReadFile(pathMiniHtml, ref contentHtml, ref directoryFileHtml))
        {
            return contentHtml.Replace("</body>", $"<script>{contentJs}</script></body>");
            
        }

        return string.Empty;
    }

    public string CreateScriptsJs(string inFilePath, string directoryCache, string sotorageNodeScriptJs)
    {
        string content = "";
        string directoryFile = "";
        if (ReadFile(inFilePath, ref content, ref directoryFile))
        {
            string readJsCodeFromHtmlFile = GetAllJsScripts(directoryFile, content);
            string cacheJsAllCode = Path.GetFullPath(Path.Combine(directoryCache, "js_all_code.js"));
            string cacheJsAllCompressCode = Path.GetFullPath(Path.Combine(directoryCache, "js_compress_all_code.js"));
            File.WriteAllText(cacheJsAllCode, readJsCodeFromHtmlFile);
            var scriptMiniferJsContent = GetscriptMiniferJs().Replace("{{OUT_FILE}}", cacheJsAllCompressCode)
                .Replace("{{IN_FILE}}", cacheJsAllCode).Replace(@"\", @"\\");
            File.WriteAllText(sotorageNodeScriptJs, scriptMiniferJsContent);


            return cacheJsAllCompressCode;
        }

        return string.Empty;
    }

    public string CreateScriptsHtml(string inFilePath, string directoryCache, string sotorageNodeScriptHtml)
    {
        string content = "";
        string directoryFile = "";


        if (ReadFile(inFilePath, ref content, ref directoryFile))
        {
            string cacheHtmlAllCode = Path.GetFullPath(Path.Combine(directoryCache, "html_all_code.html"));


            File.WriteAllText(cacheHtmlAllCode, RmoveAllScripts(content));


            string cacheHtmlCompressiCode =
                Path.GetFullPath(Path.Combine(directoryCache, "html_compress_all_code.html"));


            string script = GethtmlMinifierJs().Replace("{{OUT_FILE}}", cacheHtmlCompressiCode)
                .Replace("{{IN_FILE}}", cacheHtmlAllCode).Replace(@"\", @"\\");
            File.WriteAllText(sotorageNodeScriptHtml, script);

            return cacheHtmlCompressiCode;

           
        }

        return string.Empty;
    }


    public void RunNodeScript(string scriptPath, string nodePath = "node.exe")
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = nodePath,
            Arguments = scriptPath,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using (var process = new Process())
        {
            process.StartInfo = startInfo;

            // Запускаем процесс
            process.Start();

            // Чтение выхода и ошибок
            var output = process.StandardOutput.ReadToEnd();
            var error = process.StandardError.ReadToEnd();

            process.WaitForExit(); // Ждем окончания процесса

            // Вывод результатов
            Console.WriteLine("Вывод скрипта:");
            Console.WriteLine(output);
            if (!string.IsNullOrEmpty(error))
            {
                Console.WriteLine("Ошибка:");
                Console.WriteLine(error);
            }
        }
    }
}